/*
 * THE NEOGEN MARK, AS PARTS — generated by `scripts/trace-mark.mjs` from the
 * owner's artwork (`public/branding/neogen-mark.png`). Do not edit by hand:
 * replace the artwork and run `npm run brand`.
 *
 * Measured, not drawn: the parts rasterised together overlap the artwork's
 * own pixels 98.96% (the rest is antialiasing at the edge).
 */

/** The artwork's trimmed box: every coordinate below is in these units. */
export const MARK_BOX = { width: 389, height: 485 } as const;

/** The hub: its traced outline, each connection's mouth closed by an arc. */
export const MARK_HUB = {
  cx: 232.6,
  cy: 260.4,
  r: 76.4,
  d: "M272.5 194.3L276.5 197.7L282.5 201.9L286.5 205.5L293.6 213.5L297.5 219.3L300.9 225.5L304.7 234.5L305.8 238.5L308.2 249.5L308.9 258.5L308.6 266.5L307.7 273.5L306.5 277.5L305.8 281.5L304.9 284.5L300.9 294.5L297.7 300.5L291.2 309.5L288.2 314.5A76.4 76.4 0 0 1 251.8 335.5L251.8 335.5L246.5 335.2L237.5 335.8L231.5 335.7L219.5 334.4L208.5 332.3L203.5 332.2A76.4 76.4 0 0 1 170 306.5L170 306.5L169 303.5L164 294.5L159.7 284.5L156.2 270.5L155.2 261.5A76.4 76.4 0 0 1 172.6 211.5L172.6 211.5L187.8 199.5L198.5 193.2L206.5 189.8L214.5 187.3L218.3 186.5L224.5 184.6L227.5 183.2A76.4 76.4 0 0 1 271.8 193.5L271.8 193.5Z",
} as const;

export interface MarkArm {
  /** The outer node: a true circle. */
  node: { cx: number; cy: number; r: number };
  /** Degrees, hub → node, screen coordinates (y down). */
  angle: number;
  /** The connection's half that belongs to the hub. */
  inner: string;
  /** The connection's half that belongs to the node. */
  outer: string;
  /** Where each half grows from: just inside its own node, on the axis. */
  hubOrigin: readonly [number, number];
  nodeOrigin: readonly [number, number];
}

/** The four arms, clockwise from the top — the order the connections close. */
export const MARK_ARMS: readonly MarkArm[] = [
  {
    node: { cx: 277.5, cy: 55, r: 54.3 },
    angle: -77.7,
    inner:
      "M227.5 183.2L232.5 179.9L236 176.5L240.5 170.1L243.8 163.5L247.2 153.5L249.3 145.5L249.9 143.8L267 147.5L266.5 149.5L264.3 164.5L264 170.5L264.2 175.5L265.1 180.5L267 186.5L270 191.5L271.8 193.5L232.6 260.4Z",
    outer:
      "M249 146.6L249.3 145.5L250.5 142.1L252.7 130.5L253.2 124.5L253.1 120.5L252.6 114.5L251.2 108.5L250.6 106.5L248.3 102.5L277.5 55L287.2 109.5L281.6 114.5L279.1 117.5L274.7 124.5L272.5 129.1L270.4 134.5L266.5 149.5L266.3 150.4Z",
    hubOrigin: [247.2, 193.6],
    nodeOrigin: [267.6, 100.3],
  },
  {
    node: { cx: 337.6, cy: 433.3, r: 50.1 },
    angle: 58.7,
    inner:
      "M288.2 314.5L287 317.5L286.1 321.5L285.8 327.5L286.2 331.5L287.5 337.5L289.3 342.5L295.8 354.5L297.3 356.6L283.7 364.9L282.5 362.9L273.5 350.2L267.4 343.5L260.5 338.5L255.5 336.3L251.8 335.5L232.6 260.4Z",
    outer:
      "M295.6 354.1L295.8 354.5L297.5 356.8L299.5 360.5L306.4 370.5L310.5 375.3L313.5 378.2L317.8 381.5L322.5 384L337.6 433.3L294.4 405.5L295.4 400.5L295.6 395.5L294.9 389.5L293.9 385.5L290.6 377.5L286.5 369.5L282.5 362.9L282.1 362.3Z",
    hubOrigin: [268.1, 318.9],
    nodeOrigin: [315.8, 397.4],
  },
  {
    node: { cx: 114.7, cy: 414.4, r: 43.7 },
    angle: 127.4,
    inner:
      "M203.5 332.2L199.5 332.8L194.5 334.5L191.5 335.8L186.5 339.2L181.5 343.5L177.8 347.5L170.5 356.5L170.1 357.2L157.1 347.3L161.5 341L168.1 329.5L169.7 325.5L171.2 319.5L171.6 316.5L171.5 313.5L170 306.5L232.6 260.4Z",
    outer:
      "M171.9 354.8L170.5 356.5L162.5 368.7L159.8 373.5L158.5 376.5L156.3 383.5L155.4 388.5L155 392.5L155.7 396.5L114.7 414.4L127.5 371.2L130.5 370.7L133.5 369.5L139.5 365.9L143.5 362.7L150.9 355.5L154.5 351.1L158.9 344.8Z",
    hubOrigin: [191, 314.7],
    nodeOrigin: [136.4, 386],
  },
  {
    node: { cx: 47.8, cy: 188.8, r: 45.9 },
    angle: -158.8,
    inner:
      "M155.2 261.5L154.3 254.5L151.9 248.5L150.5 246.1L147.7 242.5L144.5 239.5L139.5 235.8L133.5 232.1L128.5 229.9L125.5 228.1L121.5 226.4L127.5 211L127.5 211.1L130.8 212.5L144.5 215.8L154.5 216.6L160.5 216L164.5 215.2L168.5 213.7L172.6 211.5L232.6 260.4Z",
    outer:
      "M124.3 227.6L116.5 224.3L108.5 221.3L103.5 220.1L97.5 219.4L91.5 219.3L84.5 220.2L81.5 221.4L47.8 188.8L94.7 188.5L97.1 192.5L99.3 195.5L101.5 197.7L106.5 201.7L112.5 205.1L119.7 208.5L127.5 211.1L130.2 212.3Z",
    hubOrigin: [168.8, 235.7],
    nodeOrigin: [83.1, 202.5],
  },
];
