import {
  BATCH_1_FLAGSHIP_PROFILES as BATCH_1,
  BATCH_2_INCRETIN_PROFILES as BATCH_2,
  BATCH_3_METABOLIC_PROFILES as BATCH_3,
  BATCH_4_RECOVERY_PROFILES as BATCH_4,
  BATCH_5_REMAINDER_PROFILES as BATCH_5,
} from "@/content/review";

import type { Reference } from "./types";

/**
 * THE REFERENCE REGISTRY.
 *
 * Adding one means reading the source and copying its metadata from the
 * source — the journal page, PubMed, Europe PMC, the DOI resolver — never from
 * a secondary list, a search snippet, or memory. `npm run check:content`
 * validates every record's identifiers, and an approved record with no DOI,
 * PMID or URL fails. A reference renders only when a published statement
 * cites it (`content/research.ts`).
 */
export const REFERENCES: readonly Reference[] = [
  /* ---- Batch 1: retatrutide ---------------------------------------------- */
  {
    id: "ref-2022-coskun-ly3437943",
    title:
      "LY3437943, a novel triple glucagon, GIP, and GLP-1 receptor agonist for glycemic control and weight loss: From discovery to clinical proof of concept",
    authors: [
      "Coskun T",
      "Urva S",
      "Roell WC",
      "Qu H",
      "Loghin C",
      "Moyers JS",
      "O'Farrell LS",
      "Briere DA",
      "Sloop KW",
      "Thomas MK",
      "Pirro V",
      "Wainscott DB",
      "Willard FS",
      "Abernathy M",
      "Morford L",
      "Du Y",
      "Benson C",
      "Gimeno RE",
      "Haupt A",
      "Milicevic Z",
    ],
    publication: "Cell Metabolism",
    year: 2022,
    doi: "10.1016/j.cmet.2022.07.013",
    pmid: "35985340",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2023-jastreboff-retatrutide-obesity",
    title: "Triple-Hormone-Receptor Agonist Retatrutide for Obesity — A Phase 2 Trial",
    authors: [
      "Jastreboff AM",
      "Kaplan LM",
      "Frías JP",
      "Wu Q",
      "Du Y",
      "Gurbuz S",
      "Coskun T",
      "Haupt A",
      "Milicevic Z",
      "Hartman ML",
      "Retatrutide Phase 2 Obesity Trial Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2023,
    doi: "10.1056/NEJMoa2301972",
    pmid: "37366315",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2023-rosenstock-retatrutide-t2d",
    title:
      "Retatrutide, a GIP, GLP-1 and glucagon receptor agonist, for people with type 2 diabetes: a randomised, double-blind, placebo and active-controlled, parallel-group, phase 2 trial conducted in the USA",
    authors: [
      "Rosenstock J",
      "Frias J",
      "Jastreboff AM",
      "Du Y",
      "Lou J",
      "Gurbuz S",
      "Thomas MK",
      "Hartman ML",
      "Haupt A",
      "Milicevic Z",
      "Coskun T",
    ],
    publication: "The Lancet",
    year: 2023,
    doi: "10.1016/S0140-6736(23)01053-X",
    pmid: "37385280",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },

  /* ---- Batch 2: tirzepatide and semaglutide ------------------------------ */
  {
    id: "ref-2018-coskun-ly3298176",
    title:
      "LY3298176, a novel dual GIP and GLP-1 receptor agonist for the treatment of type 2 diabetes mellitus: From discovery to clinical proof of concept",
    authors: [
      "Coskun T",
      "Sloop KW",
      "Loghin C",
      "Alsina-Fernandez J",
      "Urva S",
      "Bokvist KB",
      "Cui X",
      "Briere DA",
      "Cabrera O",
      "Roell WC",
      "Kuchibhotla U",
      "Moyers JS",
      "Benson CT",
      "Gimeno RE",
      "D'Alessio DA",
      "Haupt A",
    ],
    publication: "Molecular Metabolism",
    year: 2018,
    doi: "10.1016/j.molmet.2018.09.009",
    pmid: "30473097",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2021-frias-surpass-2",
    title: "Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes",
    authors: [
      "Frías JP",
      "Davies MJ",
      "Rosenstock J",
      "Pérez Manghi FC",
      "Fernández Landó L",
      "Bergman BK",
      "Liu B",
      "Cui X",
      "Brown K",
      "SURPASS-2 Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2021,
    doi: "10.1056/NEJMoa2107519",
    pmid: "34170647",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2022-jastreboff-surmount-1",
    title: "Tirzepatide Once Weekly for the Treatment of Obesity",
    authors: [
      "Jastreboff AM",
      "Aronne LJ",
      "Ahmad NN",
      "Wharton S",
      "Connery L",
      "Alves B",
      "Kiyosue A",
      "Zhang S",
      "Liu B",
      "Bunck MC",
      "Stefanski A",
      "SURMOUNT-1 Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2022,
    doi: "10.1056/NEJMoa2206038",
    pmid: "35658024",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2015-lau-semaglutide-discovery",
    title: "Discovery of the Once-Weekly Glucagon-Like Peptide-1 (GLP-1) Analogue Semaglutide",
    authors: [
      "Lau J",
      "Bloch P",
      "Schäffer L",
      "Pettersson I",
      "Spetzler J",
      "Kofoed J",
      "Madsen K",
      "Knudsen LB",
      "McGuire J",
      "Steensgaard DB",
      "Strauss HM",
      "Gram DX",
      "Knudsen SM",
      "Nielsen FS",
      "Thygesen P",
      "Reedtz-Runge S",
      "Kruse T",
    ],
    publication: "Journal of Medicinal Chemistry",
    year: 2015,
    doi: "10.1021/acs.jmedchem.5b00726",
    pmid: "26308095",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2021-wilding-step-1",
    title: "Once-Weekly Semaglutide in Adults with Overweight or Obesity",
    authors: [
      "Wilding JPH",
      "Batterham RL",
      "Calanna S",
      "Davies M",
      "Van Gaal LF",
      "Lingvay I",
      "McGowan BM",
      "Rosenstock J",
      "Tran MTD",
      "Wadden TA",
      "Wharton S",
      "Yokote K",
      "Zeuthen N",
      "Kushner RF",
      "STEP 1 Study Group",
    ],
    publication: "The New England Journal of Medicine",
    year: 2021,
    doi: "10.1056/NEJMoa2032183",
    pmid: "33567185",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },

  /* ---- Batch 3: the rest of the metabolic line --------------------------- */
  {
    id: "ref-2021-lau-cagrilintide-phase2",
    title:
      "Once-weekly cagrilintide for weight management in people with overweight and obesity: a multicentre, randomised, double-blind, placebo-controlled and active-controlled, dose-finding phase 2 trial",
    authors: [
      "Lau DCW",
      "Erichsen L",
      "Francisco AM",
      "Satylganova A",
      "le Roux CW",
      "McGowan B",
      "Pedersen SD",
      "Pietiläinen KH",
      "Rubino D",
      "Batterham RL",
    ],
    publication: "The Lancet",
    year: 2021,
    doi: "10.1016/S0140-6736(21)01751-7",
    pmid: "34798060",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2022-zimmermann-bi456906",
    title:
      "BI 456906: Discovery and preclinical pharmacology of a novel GCGR/GLP-1R dual agonist with robust anti-obesity efficacy",
    authors: [
      "Zimmermann T",
      "Thomas L",
      "Baader-Pagler T",
      "Haebel P",
      "Simon E",
      "Reindl W",
      "Bajrami B",
      "Rist W",
      "Uphues I",
      "Drucker DJ",
      "Klein H",
      "Santhanam R",
      "Hamprecht D",
      "Neubauer H",
      "Augustin R",
    ],
    publication: "Molecular Metabolism",
    year: 2022,
    doi: "10.1016/j.molmet.2022.101633",
    pmid: "36356832",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2024-sanyal-survodutide-mash",
    title: "A Phase 2 Randomized Trial of Survodutide in MASH and Fibrosis",
    authors: [
      "Sanyal AJ",
      "Bedossa P",
      "Fraessdorf M",
      "Neff GW",
      "Lawitz E",
      "Bugianesi E",
      "Anstee QM",
      "Hussain SA",
      "Newsome PN",
      "Ratziu V",
      "Hosseini-Tabatabaei A",
      "Schattenberg JM",
      "Noureddin M",
      "Alkhouri N",
      "Younes R",
      "1404-0043 Trial Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2024,
    doi: "10.1056/NEJMoa2401755",
    pmid: "38847460",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2026-gao-mazdutide-glory-2",
    title:
      "Treatment With 9-mg Mazdutide for Weight Reduction in Chinese Adults With Obesity: The GLORY-2 Randomized Clinical Trial",
    authors: [
      "Gao L",
      "Jiang H",
      "Cai H",
      "Tian J",
      "Shi B",
      "Qiu W",
      "Huang C",
      "Han J",
      "Zhang S",
      "Pang S",
      "Bi Y",
      "Chen L",
      "Gu X",
      "Han J",
      "Ma Q",
      "Deng H",
      "Wang Y",
      "Li L",
      "Han-Zhang H",
      "Qian L",
      "Ji L",
      "GLORY-2 Trial Investigators",
    ],
    publication: "JAMA",
    year: 2026,
    doi: "10.1001/jama.2026.8142",
    pmid: "42251595",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2026-zhu-mazdutide-t2d",
    title: "Mazdutide versus placebo in Chinese adults with type 2 diabetes",
    authors: [
      "Zhu D",
      "Zhao J",
      "Cai H",
      "Chu X",
      "Xiu S",
      "Song C",
      "Cheng Z",
      "Cao H",
      "Jiang H",
      "Zhang L",
      "Wang H",
      "Shi B",
      "Li Y",
      "Liu M",
      "Feng B",
      "Xue F",
      "Deng H",
      "Li H",
      "Li L",
      "Li Y",
      "Ma Q",
      "Qian L",
    ],
    publication: "Nature",
    year: 2026,
    doi: "10.1038/s41586-025-10026-w",
    pmid: "41407859",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2007-falutz-tesamorelin",
    title: "Metabolic effects of a growth hormone-releasing factor in patients with HIV",
    authors: [
      "Falutz J",
      "Allas S",
      "Blot K",
      "Potvin D",
      "Kotler D",
      "Somero M",
      "Berger D",
      "Brown S",
      "Richmond G",
      "Fessel J",
      "Turner R",
      "Grinspoon S",
    ],
    publication: "The New England Journal of Medicine",
    year: 2007,
    doi: "10.1056/NEJMoa072375",
    pmid: "18057338",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2015-cox-aod9604",
    title: "Detection and in vitro metabolism of AOD9604",
    authors: ["Cox HD", "Smeal SJ", "Hughes CM", "Cox JE", "Eichner D"],
    publication: "Drug Testing and Analysis",
    year: 2015,
    doi: "10.1002/dta.1715",
    pmid: "25208511",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2000-ng-aod9604-zucker",
    title: "Metabolic studies of a synthetic lipolytic domain (AOD9604) of human growth hormone",
    authors: ["Ng FM", "Sun J", "Sharma L", "Libinaka R", "Jiang WJ", "Gianello R"],
    publication: "Hormone Research",
    year: 2000,
    doi: "10.1159/000053183",
    pmid: "11146367",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2001-heffernan-aod9604-mice",
    title:
      "The effects of human GH and its lipolytic fragment (AOD9604) on lipid metabolism following chronic treatment in obese mice and beta(3)-AR knock-out mice",
    authors: [
      "Heffernan M",
      "Summers RJ",
      "Thorburn A",
      "Ogru E",
      "Gianello R",
      "Jiang WJ",
      "Ng FM",
    ],
    publication: "Endocrinology",
    year: 2001,
    doi: "10.1210/endo.142.12.8522",
    pmid: "11713213",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2018-neelakantan-nnmt-inhibitors",
    title:
      "Selective and membrane-permeable small molecule inhibitors of nicotinamide N-methyltransferase reverse high fat diet-induced obesity in mice",
    authors: [
      "Neelakantan H",
      "Vance V",
      "Wetzel MD",
      "Wang HL",
      "McHardy SF",
      "Finnerty CC",
      "Hommel JD",
      "Watowich SJ",
    ],
    publication: "Biochemical Pharmacology",
    year: 2018,
    doi: "10.1016/j.bcp.2017.11.007",
    pmid: "29155147",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2021-roberti-nnmt",
    title:
      "Nicotinamide N-methyltransferase: At the crossroads between cellular metabolism and epigenetic regulation",
    authors: ["Roberti A", "Fernández AF", "Fraga MF"],
    publication: "Molecular Metabolism",
    year: 2021,
    doi: "10.1016/j.molmet.2021.101165",
    pmid: "33453420",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },
  {
    id: "ref-2023-billon-slu-pp-332",
    title:
      "Synthetic ERRα/β/γ Agonist Induces an ERRα-Dependent Acute Aerobic Exercise Response and Enhances Exercise Capacity",
    authors: [
      "Billon C",
      "Sitaula S",
      "Banerjee S",
      "Welch R",
      "Elgendy B",
      "Hegazy L",
      "Oh TG",
      "Kazantzis M",
      "Chatterjee A",
      "Chrivia J",
      "Hayes ME",
      "Xu W",
      "Hamilton A",
      "Huss JM",
      "Zhang L",
      "Walker JK",
      "Downes M",
      "Evans RM",
      "Burris TP",
    ],
    publication: "ACS Chemical Biology",
    year: 2023,
    doi: "10.1021/acschembio.2c00720",
    pmid: "36988910",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2004-kolonin-adipose-ablation",
    title: "Reversal of obesity by targeted ablation of adipose tissue",
    authors: ["Kolonin MG", "Saha PK", "Chan L", "Pasqualini R", "Arap W"],
    publication: "Nature Medicine",
    year: 2004,
    doi: "10.1038/nm1048",
    pmid: "15133506",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2011-barnhart-adipotide-monkeys",
    title:
      "A peptidomimetic targeting white fat causes weight loss and improved insulin resistance in obese monkeys",
    authors: [
      "Barnhart KF",
      "Christianson DR",
      "Hanley PW",
      "Driessen WH",
      "Bernacky BJ",
      "Baze WB",
      "Wen S",
      "Tian M",
      "Ma J",
      "Kolonin MG",
      "Saha PK",
      "Do KA",
      "Hulvat JF",
      "Gelovani JG",
      "Chan L",
      "Arap W",
      "Pasqualini R",
    ],
    publication: "Science Translational Medicine",
    year: 2011,
    doi: "10.1126/scitranslmed.3002621",
    pmid: "22072637",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2016-longo-carnitine-transport",
    title: "Carnitine transport and fatty acid oxidation",
    authors: ["Longo N", "Frigeni M", "Pasquali M"],
    publication: "Biochimica et Biophysica Acta",
    year: 2016,
    doi: "10.1016/j.bbamcr.2016.01.023",
    pmid: "26828774",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },
  {
    id: "ref-2016-pooyandjoo-carnitine-meta",
    title:
      "The effect of (L-)carnitine on weight loss in adults: a systematic review and meta-analysis of randomized controlled trials",
    authors: ["Pooyandjoo M", "Nouhi M", "Shab-Bidar S", "Djafarian K", "Olyaeemanesh A"],
    publication: "Obesity Reviews",
    year: 2016,
    doi: "10.1111/obr.12436",
    pmid: "27335245",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },

  /* ---- Batch 5: the remainder -------------------------------------------- */
  {
    id: "ref-2026-dominikowski-gh-igf1-peptides",
    title:
      "The emerging landscape of performance-enhancing peptides modulating GH-IGF1 axis: bridging the gap between clinical evidence and patient self-administration",
    authors: [
      "Dominikowski A",
      "Rękoś Z",
      "Olejarz M",
      "Szczepanek-Parulska E",
      "Domin R",
      "Ruchała M",
    ],
    publication: "Frontiers in Endocrinology",
    year: 2026,
    doi: "10.3389/fendo.2026.1822475",
    pmid: "42395176",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-1998-raun-ipamorelin",
    title: "Ipamorelin, the first selective growth hormone secretagogue",
    authors: [
      "Raun K",
      "Hansen BS",
      "Johansen NL",
      "Thøgersen H",
      "Madsen K",
      "Ankersen M",
      "Andersen PH",
    ],
    publication: "European Journal of Endocrinology",
    year: 1998,
    doi: "10.1530/eje.0.1390552",
    pmid: "9849822",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2006-teichman-cjc-1295",
    title:
      "Prolonged stimulation of growth hormone (GH) and insulin-like growth factor I secretion by CJC-1295, a long-acting analog of GH-releasing hormone, in healthy adults",
    authors: ["Teichman SL", "Neale A", "Lawrence B", "Gagnon C", "Castaigne JP", "Frohman LA"],
    publication: "The Journal of Clinical Endocrinology and Metabolism",
    year: 2006,
    doi: "10.1210/jc.2005-1536",
    pmid: "16352683",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2019-timms-cjc-1295-detection",
    title: "A method for confirming CJC-1295 abuse in equine plasma samples by LC-MS/MS",
    authors: ["Timms M", "Ganio K", "Steel R"],
    publication: "Drug Testing and Analysis",
    year: 2019,
    doi: "10.1002/dta.2599",
    pmid: "30938069",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2017-ohara-ghrp-2-test",
    title:
      "Laparoscopic Sleeve Gastrectomy Resolves Low GHRP-2-Stimulated Growth Hormone Levels in Obese Patients",
    authors: [
      "Ohara E",
      "Tokuyama H",
      "Kitamoto T",
      "Kitahara A",
      "Hayashi A",
      "Hayashi H",
      "Takemoto M",
      "Yokote K",
    ],
    publication: "Obesity Surgery",
    year: 2017,
    doi: "10.1007/s11695-017-2769-4",
    pmid: "28623445",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-wang-ghrp-6-infarct",
    title:
      "Growth Hormone-Releasing Peptide-6 (GHRP-6) Ameliorates Post-Infarct Ventricular Remodeling and Systolic Dysfunction",
    authors: [
      "Wang L",
      "Rodriguez-Ulloa A",
      "Berlanga-Acosta J",
      "García-Ojalvo A",
      "Abreu-Cruz A",
      "Gonzalez-López LJ",
      "Besada-López V",
      "Ramos-Gómez Y",
      "Guillén-Nieto G",
      "Jiang B",
    ],
    publication: "Pharmaceuticals",
    year: 2026,
    doi: "10.3390/ph19030468",
    pmid: "41901314",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2023-liu-mechano-growth-factor",
    title:
      "The role of mechano growth factor in chondrocytes and cartilage defects: a concise review",
    authors: ["Liu Y", "Duan M", "Zhang D", "Xie J"],
    publication: "Acta Biochimica et Biophysica Sinica",
    year: 2023,
    doi: "10.3724/abbs.2023086",
    pmid: "37171185",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2019-levolger-alk4-5-cachexia",
    title:
      "Inhibition of activin-like kinase 4/5 attenuates cancer cachexia associated muscle wasting",
    authors: [
      "Levolger S",
      "Wiemer EAC",
      "van Vugt JLA",
      "Huisman SA",
      "van Vledder MG",
      "van Damme-van Engel S",
      "Ambagtsheer G",
      "IJzermans JNM",
      "de Bruin RWF",
    ],
    publication: "Scientific Reports",
    year: 2019,
    doi: "10.1038/s41598-019-46178-9",
    pmid: "31285507",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-1997-mcpherron-gdf-8",
    title: "Regulation of skeletal muscle mass in mice by a new TGF-beta superfamily member",
    authors: ["McPherron AC", "Lawler AM", "Lee SJ"],
    publication: "Nature",
    year: 1997,
    doi: "10.1038/387083a0",
    pmid: "9139826",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-cadena-ace-031-marmoset",
    title:
      "ACE-031, a soluble activin type IIB receptor, increases muscle mass and strength in the common marmoset",
    authors: [
      "Cadena SM",
      "Bogdanovich S",
      "Khurana TS",
      "Pullen A",
      "Pearsall RS",
      "Curran E",
      "Faucette R",
      "Lane J",
      "Seehra J",
      "Lachey JL",
      "Mizener AD",
      "Pistilli EE",
    ],
    publication: "PLoS One",
    year: 2026,
    doi: "10.1371/journal.pone.0342666",
    pmid: "41686840",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2011-george-kisspeptin-10",
    title: "Kisspeptin-10 is a potent stimulator of LH and increases pulse frequency in men",
    authors: [
      "George JT",
      "Veldhuis JD",
      "Roseweir AK",
      "Newton CL",
      "Faccenda E",
      "Millar RP",
      "Anderson RA",
    ],
    publication: "The Journal of Clinical Endocrinology and Metabolism",
    year: 2011,
    doi: "10.1210/jc.2011-0089",
    pmid: "21632807",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2019-kingsberg-bremelanotide",
    title:
      "Bremelanotide for the Treatment of Hypoactive Sexual Desire Disorder: Two Randomized Phase 3 Trials",
    authors: [
      "Kingsberg SA",
      "Clayton AH",
      "Portman D",
      "Williams LA",
      "Krop J",
      "Jordan R",
      "Lucas J",
      "Simon JA",
    ],
    publication: "Obstetrics and Gynecology",
    year: 2019,
    doi: "10.1097/AOG.0000000000003500",
    pmid: "31599840",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-feng-mc4r-modulators",
    title:
      "Rationale of renewed efforts in developing MC4R modulators to treat metabolic disorders",
    authors: ["Feng W", "Zhou Q", "Wang MW"],
    publication: "Acta Pharmaceutica Sinica B",
    year: 2026,
    doi: "10.1016/j.apsb.2026.06.035",
    pmid: "42592034",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2018-jurek-oxytocin-receptor",
    title: "The Oxytocin Receptor: From Intracellular Signaling to Behavior",
    authors: ["Jurek B", "Neumann ID"],
    publication: "Physiological Reviews",
    year: 2018,
    doi: "10.1152/physrev.00031.2017",
    pmid: "29897293",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2025-shoaib-hcg-male-infertility",
    title:
      "Use of Human Chorionic Gonadotropin (HCG) or HCG-Combined Treatments in Male Infertility: A Systematic Review",
    authors: ["Shoaib H", "Duffy J", "Ahmed K"],
    publication: "Cureus",
    year: 2025,
    doi: "10.7759/cureus.94003",
    pmid: "41210019",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-dawlaty-vip-pacap-sepsis",
    title:
      "A Historical Review of Vasoactive Intestinal Peptide and Pituitary Adenylate Cyclase-Activating Polypeptide in Sepsis",
    authors: ["Dawlaty R", "Entsie P", "Amoafo EB", "Liverani E", "Dorsam GP"],
    publication: "Biology",
    year: 2026,
    doi: "10.3390/biology15090663",
    pmid: "42117802",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2021-covarrubias-nad-ageing",
    title: "NAD+ metabolism and its roles in cellular processes during ageing",
    authors: ["Covarrubias AJ", "Perrone R", "Grozio A", "Verdin E"],
    publication: "Nature Reviews Molecular Cell Biology",
    year: 2021,
    doi: "10.1038/s41580-020-00313-x",
    pmid: "33353981",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2015-lee-mots-c",
    title:
      "The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis and reduces obesity and insulin resistance",
    authors: [
      "Lee C",
      "Zeng J",
      "Drew BG",
      "Sallam T",
      "Martin-Montalvo A",
      "Wan J",
      "Kim SJ",
      "Mehta H",
      "Hevener AL",
      "de Cabo R",
      "Cohen P",
    ],
    publication: "Cell Metabolism",
    year: 2015,
    doi: "10.1016/j.cmet.2015.02.009",
    pmid: "25738459",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2014-chai-humanin-alzheimer",
    title:
      "Humanin attenuates Alzheimer-like cognitive deficits and pathological changes induced by amyloid β-peptide",
    authors: [
      "Chai GS",
      "Duan DX",
      "Ma RH",
      "Shen JY",
      "Li HL",
      "Ma ZW",
      "Luo Y",
      "Wang L",
      "Qi XH",
      "Wang Q",
      "Wang JZ",
      "Wei Z",
      "Mousseau DD",
      "Wang L",
      "Liu G",
    ],
    publication: "Neuroscience Bulletin",
    year: 2014,
    doi: "10.1007/s12264-014-1479-3",
    pmid: "25391447",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2014-szeto-cardiolipin",
    title:
      "First-in-class cardiolipin-protective compound as a therapeutic agent to restore mitochondrial bioenergetics",
    authors: ["Szeto HH"],
    publication: "British Journal of Pharmacology",
    year: 2014,
    doi: "10.1111/bph.12461",
    pmid: "24117165",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2017-baar-foxo4-senescence",
    title:
      "Targeted Apoptosis of Senescent Cells Restores Tissue Homeostasis in Response to Chemotoxicity and Aging",
    authors: [
      "Baar MP",
      "Brandt RMC",
      "Putavet DA",
      "Klein JDD",
      "Derks KWJ",
      "Bourgeois BRM",
      "Stryeck S",
      "Rijksen Y",
      "van Willigenburg H",
      "Feijtel DA",
      "van der Pluijm I",
      "Essers J",
      "van Cappellen WA",
      "van IJcken WF",
      "Houtsmuller AB",
      "Pothof J",
      "de Bruin RWF",
      "Madl T",
      "Hoeijmakers JHJ",
      "Campisi J",
      "de Keizer PLJ",
    ],
    publication: "Cell",
    year: 2017,
    doi: "10.1016/j.cell.2017.02.031",
    pmid: "28340339",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2009-forman-glutathione",
    title: "Glutathione: overview of its protective roles, measurement, and biosynthesis",
    authors: ["Forman HJ", "Zhang H", "Rinna A"],
    publication: "Molecular Aspects of Medicine",
    year: 2009,
    doi: "10.1016/j.mam.2008.08.006",
    pmid: "18796312",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-mavrych-gerontology-peptides",
    title: "Therapeutic peptides in gerontology: mechanisms and applications for healthy aging",
    authors: ["Mavrych V", "Shypilova I", "Bolgova O"],
    publication: "Frontiers in Aging",
    year: 2026,
    doi: "10.3389/fragi.2026.1790247",
    pmid: "42021992",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2018-cipolla-neto-melatonin",
    title: "Melatonin as a Hormone: New Physiological and Clinical Insights",
    authors: ["Cipolla-Neto J", "Amaral FGD"],
    publication: "Endocrine Reviews",
    year: 2018,
    doi: "10.1210/er.2018-00084",
    pmid: "30215696",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2025-kolbaev-semax-calcium",
    title:
      "The Effect of Peptide Semax, an ACTH(4-10) Analogue, on Intracellular Calcium Dynamics in Rat Brain Slices",
    authors: ["Kolbaev SN", "Sharonova IN", "Skrebitsky VG"],
    publication: "Bulletin of Experimental Biology and Medicine",
    year: 2025,
    doi: "10.1007/s10517-025-06501-z",
    pmid: "41171324",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2025-radchenko-semax-review",
    title:
      "The Potential of the Peptide Drug Semax and Its Derivative for Correcting Pathological Impairments in Alzheimer's Disease",
    authors: [
      "Radchenko AI",
      "Kuzubova EV",
      "Apostol AA",
      "Mitkevich VA",
      "Andreeva LA",
      "Limborska SA",
      "Stepenko YV",
      "Shmigerova VS",
      "Solin AV",
      "Korokin MV",
      "Pokrovskii MV",
      "Myasoedov NF",
      "Makarov AA",
    ],
    publication: "Acta Naturae",
    year: 2025,
    doi: "10.32607/actanaturae.27808",
    pmid: "41479572",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2022-konstantinopolsky-selank",
    title:
      "Selank, a Peptide Analog of Tuftsin, Attenuates Aversive Signs of Morphine Withdrawal in Rats",
    authors: ["Konstantinopolsky MA", "Chernyakova IV", "Kolik LG"],
    publication: "Bulletin of Experimental Biology and Medicine",
    year: 2022,
    doi: "10.1007/s10517-022-05624-x",
    pmid: "36322304",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-staszewski-cerebrolysin-evt",
    title:
      "Cerebrolysin after Endovascular Thrombectomy in Stroke: 12-Month Functional Outcomes in a Propensity-Matched Cohort",
    authors: [
      "Staszewski J",
      "Dębiec A",
      "Gniadek-Olejniczak K",
      "Stępień A",
      "Piusinska-Macoch R",
      "Strilciuc S",
      "Balo D",
      "Harston G",
      "Brzozowski K",
      "Zięcina P",
      "Narloch J",
      "Wierzbicki M",
      "Piasecki P",
    ],
    publication: "Translational Stroke Research",
    year: 2026,
    doi: "10.1007/s12975-026-01414-z",
    pmid: "41739286",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2024-wells-dihexa-huntington",
    title:
      "Effects of an Angiotensin IV Analog on 3-Nitropropionic Acid-Induced Huntington's Disease-Like Symptoms in Rats",
    authors: ["Wells RG", "Azzam AF", "Hiller AL", "Sardinia MF"],
    publication: "Journal of Huntington's Disease",
    year: 2024,
    doi: "10.3233/jhd-231507",
    pmid: "38489193",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2024-mottolese-p021-cntf-mimetic",
    title:
      "Effects of a ciliary neurotrophic factor (CNTF) small-molecule peptide mimetic in an in vitro and in vivo model of CDKL5 deficiency disorder",
    authors: [
      "Mottolese N",
      "Loi M",
      "Trazzi S",
      "Tassinari M",
      "Uguagliati B",
      "Candini G",
      "Iqbal K",
      "Medici G",
      "Ciani E",
    ],
    publication: "Journal of Neurodevelopmental Disorders",
    year: 2024,
    doi: "10.1186/s11689-024-09583-4",
    pmid: "39592934",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2015-langendonk-afamelanotide",
    title: "Afamelanotide for Erythropoietic Protoporphyria",
    authors: [
      "Langendonk JG",
      "Balwani M",
      "Anderson KE",
      "Bonkovsky HL",
      "Anstey AV",
      "Bissell DM",
      "Bloomer J",
      "Edwards C",
      "Neumann NJ",
      "Parker C",
      "Phillips JD",
      "Lim HW",
      "Hamzavi I",
      "Deybach JC",
      "Kauppinen R",
      "Rhodes LE",
      "Frank J",
      "Murphy GM",
      "Karstens FPJ",
      "Sijbrands EJG",
      "de Rooij FWM",
      "Lebwohl M",
      "Naik H",
      "Goding CR",
      "Wilson JHP",
      "Desnick RJ",
    ],
    publication: "The New England Journal of Medicine",
    year: 2015,
    doi: "10.1056/NEJMoa1411481",
    pmid: "26132941",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-bonchev-melanotan-ii",
    title: "Changes in Oral Mucosa Associated with Melanotan II Injections: A Case Report",
    authors: ["Bonchev A"],
    publication: "Life",
    year: 2026,
    doi: "10.3390/life16020265",
    pmid: "41752902",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },
  {
    id: "ref-2017-green-b12-deficiency",
    title: "Vitamin B12 deficiency",
    authors: [
      "Green R",
      "Allen LH",
      "Bjørke-Monsen AL",
      "Brito A",
      "Guéant JL",
      "Miller JW",
      "Molloy AM",
      "Nexo E",
      "Stabler S",
      "Toh BH",
      "Ueland PM",
      "Yajnik C",
    ],
    publication: "Nature Reviews Disease Primers",
    year: 2017,
    doi: "10.1038/nrdp.2017.40",
    pmid: "28660890",
    url: null,
    sourceType: "review-article",
    status: BATCH_5,
  },
  {
    id: "ref-2026-zhuang-dermorphin-fentanyl",
    title: "Dermorphin blocks apneic response to intravenous bolus injection of fentanyl",
    authors: ["Zhuang J", "Gao X", "Shi S", "Xu F"],
    publication: "Toxicology and Applied Pharmacology",
    year: 2026,
    doi: "10.1016/j.taap.2026.117785",
    pmid: "41802575",
    url: null,
    sourceType: "journal-article",
    status: BATCH_5,
  },

  /* ---- Batch 4: the recovery area ---------------------------------------- */
  {
    id: "ref-2025-simonova-thymosin-alpha-1",
    title: "Aging and Thymosin Alpha-1",
    authors: [
      "Simonova MA",
      "Ivanov I",
      "Shoshina NS",
      "Komyakova AM",
      "Makarov DA",
      "Baranovskii DS",
      "Klabukov ID",
      "Telepenina KP",
      "Atiakshin DA",
      "Shegay PV",
      "Kaprin AD",
      "Stepanenko VN",
    ],
    publication: "International Journal of Molecular Sciences",
    year: 2025,
    doi: "10.3390/ijms262311470",
    pmid: "41373628",
    url: null,
    sourceType: "review-article",
    status: BATCH_4,
  },
  {
    id: "ref-2013-wu-etass",
    title:
      "The efficacy of thymosin alpha 1 for severe sepsis (ETASS): a multicenter, single-blind, randomized and controlled trial",
    authors: [
      "Wu J",
      "Zhou L",
      "Liu J",
      "Ma G",
      "Kou Q",
      "He Z",
      "Chen J",
      "Ou-Yang B",
      "Chen M",
      "Li Y",
      "Wu X",
      "Gu B",
      "Chen L",
      "Zou Z",
      "Qiang X",
      "Chen Y",
      "Lin A",
      "Zhang G",
      "Guan X",
    ],
    publication: "Critical Care",
    year: 2013,
    doi: "10.1186/cc11932",
    pmid: "23327199",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2008-dalmasso-kpv-pept1",
    title: "PepT1-mediated tripeptide KPV uptake reduces intestinal inflammation",
    authors: [
      "Dalmasso G",
      "Charrier-Hisamuddin L",
      "Nguyen HT",
      "Yan Y",
      "Sitaraman S",
      "Merlin D",
    ],
    publication: "Gastroenterology",
    year: 2008,
    doi: "10.1053/j.gastro.2007.10.026",
    pmid: "18061177",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2008-kannengiesser-kpv-ibd",
    title:
      "Melanocortin-derived tripeptide KPV has anti-inflammatory potential in murine models of inflammatory bowel disease",
    authors: [
      "Kannengiesser K",
      "Maaser C",
      "Heidemann J",
      "Luegering A",
      "Ross M",
      "Brzoska T",
      "Bohm M",
      "Luger TA",
      "Domschke W",
      "Kucharzik T",
    ],
    publication: "Inflammatory Bowel Diseases",
    year: 2008,
    doi: "10.1002/ibd.20334",
    pmid: "18092346",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2008-brines-helix-b-peptides",
    title:
      "Nonerythropoietic, tissue-protective peptides derived from the tertiary structure of erythropoietin",
    authors: [
      "Brines M",
      "Patel NS",
      "Villa P",
      "Brines C",
      "Mennini T",
      "De Paola M",
      "Erbayraktar Z",
      "Erbayraktar S",
      "Sepodes B",
      "Thiemermann C",
      "Ghezzi P",
      "Yamin M",
      "Hand CC",
      "Xie QW",
      "Coleman T",
      "Cerami A",
    ],
    publication: "Proceedings of the National Academy of Sciences",
    year: 2008,
    doi: "10.1073/pnas.0805594105",
    pmid: "18676614",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2013-dahan-ara290-sarcoidosis",
    title:
      "ARA 290 improves symptoms in patients with sarcoidosis-associated small nerve fiber loss and increases corneal nerve fiber density",
    authors: [
      "Dahan A",
      "Dunne A",
      "Swartjes M",
      "Proto PL",
      "Heij L",
      "Vogels O",
      "van Velzen M",
      "Sarton E",
      "Niesters M",
      "Tannemaat MR",
      "Cerami A",
      "Brines M",
    ],
    publication: "Molecular Medicine",
    year: 2013,
    doi: "10.2119/molmed.2013.00122",
    pmid: "24136731",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2003-heilborn-ll37-reepithelialisation",
    title:
      "The cathelicidin anti-microbial peptide LL-37 is involved in re-epithelialization of human skin wounds and is lacking in chronic ulcer epithelium",
    authors: [
      "Heilborn JD",
      "Nilsson MF",
      "Kratz G",
      "Weber G",
      "Sørensen O",
      "Borregaard N",
      "Ståhle-Bäckdahl M",
    ],
    publication: "The Journal of Investigative Dermatology",
    year: 2003,
    doi: "10.1046/j.1523-1747.2003.12069.x",
    pmid: "12603850",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2007-pyo-ahk-cu-hair",
    title: "The effect of tripeptide-copper complex on human hair growth in vitro",
    authors: ["Pyo HK", "Yoo HG", "Won CH", "Lee SH", "Kang YJ", "Eun HC", "Cho KH", "Kim KH"],
    publication: "Archives of Pharmacal Research",
    year: 2007,
    doi: "10.1007/bf02978833",
    pmid: "17703734",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },
  {
    id: "ref-2023-linkova-thymalin-dipeptides",
    title:
      "The Influence of KE and EW Dipeptides in the Composition of the Thymalin Drug on Gene Expression and Protein Synthesis Involved in the Pathogenesis of COVID-19",
    authors: [
      "Linkova N",
      "Khavinson V",
      "Diatlova A",
      "Petukhov M",
      "Vladimirova E",
      "Sukhareva M",
      "Ilina A",
    ],
    publication: "International Journal of Molecular Sciences",
    year: 2023,
    doi: "10.3390/ijms241713377",
    pmid: "37686182",
    url: null,
    sourceType: "journal-article",
    status: BATCH_4,
  },

  /* ---- Batch 1: GHK-Cu --------------------------------------------------- */
  {
    id: "ref-2015-pickart-ghk-skin",
    title: "GHK Peptide as a Natural Modulator of Multiple Cellular Pathways in Skin Regeneration",
    authors: ["Pickart L", "Vasquez-Soltero JM", "Margolina A"],
    publication: "BioMed Research International",
    year: 2015,
    doi: "10.1155/2015/648108",
    pmid: "26236730",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-2018-pickart-ghk-cu-gene-data",
    title:
      "Regenerative and Protective Actions of the GHK-Cu Peptide in the Light of the New Gene Data",
    authors: ["Pickart L", "Margolina A"],
    publication: "International Journal of Molecular Sciences",
    year: 2018,
    doi: "10.3390/ijms19071987",
    pmid: "29986520",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },

  /* ---- Batch 1: BPC-157 and TB-500 --------------------------------------- */
  {
    id: "ref-2025-vasireddi-bpc157-review",
    title: "Emerging Use of BPC-157 in Orthopaedic Sports Medicine: A Systematic Review",
    authors: [
      "Vasireddi N",
      "Hahamyan H",
      "Salata MJ",
      "Karns M",
      "Calcei JG",
      "Voos JE",
      "Apostolakos JM",
    ],
    publication: "HSS Journal",
    year: 2025,
    doi: "10.1177/15563316251355551",
    pmid: "40756949",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-2012-goldstein-thymosin-b4",
    title:
      "Thymosin β4: a multi-functional regenerative peptide. Basic properties and clinical applications",
    authors: ["Goldstein AL", "Hannappel E", "Sosne G", "Kleinman HK"],
    publication: "Expert Opinion on Biological Therapy",
    year: 2012,
    doi: "10.1517/14712598.2012.634793",
    pmid: "22074294",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-1999-malinda-thymosin-b4-wound",
    title: "Thymosin beta4 accelerates wound healing",
    authors: [
      "Malinda KM",
      "Sidhu GS",
      "Mani H",
      "Banaudha K",
      "Maheshwari RK",
      "Goldstein AL",
      "Kleinman HK",
    ],
    publication: "The Journal of Investigative Dermatology",
    year: 1999,
    doi: "10.1046/j.1523-1747.1999.00708.x",
    pmid: "10469335",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2026-bicer-bpc157-tb500-achilles",
    title:
      "Effects of BPC-157 and TB-500 on Achilles tendon healing in rats: A histopathological and biomechanical study",
    authors: [
      "Biçer O",
      "Adanir O",
      "Güleryüz Y",
      "Balci EC",
      "Dinçel YM",
      "Yenigün MY",
      "Aydin C",
      "Bayrak BY",
    ],
    publication: "Joint Diseases and Related Surgery",
    year: 2026,
    doi: "10.52312/jdrs.2026.2951",
    pmid: "42542926",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },

  /* ---- Batch 1: shared --------------------------------------------------- */
  {
    id: "ref-2026-tewari-peptide-supplements",
    title: "Peptide Supplements and Their Therapeutic Applications in Sports Medicine",
    authors: ["Tewari K", "Liu TP", "Im C", "Hamad C", "Petrigliano F", "Cheung EC", "Kremen TJ"],
    publication: "The American Journal of Sports Medicine",
    year: 2026,
    doi: "10.1177/03635465261464420",
    pmid: "42578445",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
];
