import {
  BATCH_1_FLAGSHIP_PROFILES as BATCH_1,
  BATCH_2_INCRETIN_PROFILES as BATCH_2,
  BATCH_3_METABOLIC_PROFILES as BATCH_3,
} from "@/content/review";

import type { Reference } from "./types";

/**
 * THE REFERENCE REGISTRY.
 *
 * Adding one means reading the source and copying its metadata from the
 * source — the journal page, PubMed, Europe PMC, the DOI resolver — never from
 * a secondary list, a search snippet, or memory. `npm run check:content`
 * validates every record's identifiers, and an approved record with no DOI,
 * PMID or URL fails. A reference renders only when a published statement
 * cites it (`content/research.ts`).
 */
export const REFERENCES: readonly Reference[] = [
  /* ---- Batch 1: retatrutide ---------------------------------------------- */
  {
    id: "ref-2022-coskun-ly3437943",
    title:
      "LY3437943, a novel triple glucagon, GIP, and GLP-1 receptor agonist for glycemic control and weight loss: From discovery to clinical proof of concept",
    authors: [
      "Coskun T",
      "Urva S",
      "Roell WC",
      "Qu H",
      "Loghin C",
      "Moyers JS",
      "O'Farrell LS",
      "Briere DA",
      "Sloop KW",
      "Thomas MK",
      "Pirro V",
      "Wainscott DB",
      "Willard FS",
      "Abernathy M",
      "Morford L",
      "Du Y",
      "Benson C",
      "Gimeno RE",
      "Haupt A",
      "Milicevic Z",
    ],
    publication: "Cell Metabolism",
    year: 2022,
    doi: "10.1016/j.cmet.2022.07.013",
    pmid: "35985340",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2023-jastreboff-retatrutide-obesity",
    title: "Triple-Hormone-Receptor Agonist Retatrutide for Obesity — A Phase 2 Trial",
    authors: [
      "Jastreboff AM",
      "Kaplan LM",
      "Frías JP",
      "Wu Q",
      "Du Y",
      "Gurbuz S",
      "Coskun T",
      "Haupt A",
      "Milicevic Z",
      "Hartman ML",
      "Retatrutide Phase 2 Obesity Trial Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2023,
    doi: "10.1056/NEJMoa2301972",
    pmid: "37366315",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2023-rosenstock-retatrutide-t2d",
    title:
      "Retatrutide, a GIP, GLP-1 and glucagon receptor agonist, for people with type 2 diabetes: a randomised, double-blind, placebo and active-controlled, parallel-group, phase 2 trial conducted in the USA",
    authors: [
      "Rosenstock J",
      "Frias J",
      "Jastreboff AM",
      "Du Y",
      "Lou J",
      "Gurbuz S",
      "Thomas MK",
      "Hartman ML",
      "Haupt A",
      "Milicevic Z",
      "Coskun T",
    ],
    publication: "The Lancet",
    year: 2023,
    doi: "10.1016/S0140-6736(23)01053-X",
    pmid: "37385280",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },

  /* ---- Batch 2: tirzepatide and semaglutide ------------------------------ */
  {
    id: "ref-2018-coskun-ly3298176",
    title:
      "LY3298176, a novel dual GIP and GLP-1 receptor agonist for the treatment of type 2 diabetes mellitus: From discovery to clinical proof of concept",
    authors: [
      "Coskun T",
      "Sloop KW",
      "Loghin C",
      "Alsina-Fernandez J",
      "Urva S",
      "Bokvist KB",
      "Cui X",
      "Briere DA",
      "Cabrera O",
      "Roell WC",
      "Kuchibhotla U",
      "Moyers JS",
      "Benson CT",
      "Gimeno RE",
      "D'Alessio DA",
      "Haupt A",
    ],
    publication: "Molecular Metabolism",
    year: 2018,
    doi: "10.1016/j.molmet.2018.09.009",
    pmid: "30473097",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2021-frias-surpass-2",
    title: "Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes",
    authors: [
      "Frías JP",
      "Davies MJ",
      "Rosenstock J",
      "Pérez Manghi FC",
      "Fernández Landó L",
      "Bergman BK",
      "Liu B",
      "Cui X",
      "Brown K",
      "SURPASS-2 Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2021,
    doi: "10.1056/NEJMoa2107519",
    pmid: "34170647",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2022-jastreboff-surmount-1",
    title: "Tirzepatide Once Weekly for the Treatment of Obesity",
    authors: [
      "Jastreboff AM",
      "Aronne LJ",
      "Ahmad NN",
      "Wharton S",
      "Connery L",
      "Alves B",
      "Kiyosue A",
      "Zhang S",
      "Liu B",
      "Bunck MC",
      "Stefanski A",
      "SURMOUNT-1 Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2022,
    doi: "10.1056/NEJMoa2206038",
    pmid: "35658024",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2015-lau-semaglutide-discovery",
    title: "Discovery of the Once-Weekly Glucagon-Like Peptide-1 (GLP-1) Analogue Semaglutide",
    authors: [
      "Lau J",
      "Bloch P",
      "Schäffer L",
      "Pettersson I",
      "Spetzler J",
      "Kofoed J",
      "Madsen K",
      "Knudsen LB",
      "McGuire J",
      "Steensgaard DB",
      "Strauss HM",
      "Gram DX",
      "Knudsen SM",
      "Nielsen FS",
      "Thygesen P",
      "Reedtz-Runge S",
      "Kruse T",
    ],
    publication: "Journal of Medicinal Chemistry",
    year: 2015,
    doi: "10.1021/acs.jmedchem.5b00726",
    pmid: "26308095",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },
  {
    id: "ref-2021-wilding-step-1",
    title: "Once-Weekly Semaglutide in Adults with Overweight or Obesity",
    authors: [
      "Wilding JPH",
      "Batterham RL",
      "Calanna S",
      "Davies M",
      "Van Gaal LF",
      "Lingvay I",
      "McGowan BM",
      "Rosenstock J",
      "Tran MTD",
      "Wadden TA",
      "Wharton S",
      "Yokote K",
      "Zeuthen N",
      "Kushner RF",
      "STEP 1 Study Group",
    ],
    publication: "The New England Journal of Medicine",
    year: 2021,
    doi: "10.1056/NEJMoa2032183",
    pmid: "33567185",
    url: null,
    sourceType: "journal-article",
    status: BATCH_2,
  },

  /* ---- Batch 3: the rest of the metabolic line --------------------------- */
  {
    id: "ref-2021-lau-cagrilintide-phase2",
    title:
      "Once-weekly cagrilintide for weight management in people with overweight and obesity: a multicentre, randomised, double-blind, placebo-controlled and active-controlled, dose-finding phase 2 trial",
    authors: [
      "Lau DCW",
      "Erichsen L",
      "Francisco AM",
      "Satylganova A",
      "le Roux CW",
      "McGowan B",
      "Pedersen SD",
      "Pietiläinen KH",
      "Rubino D",
      "Batterham RL",
    ],
    publication: "The Lancet",
    year: 2021,
    doi: "10.1016/S0140-6736(21)01751-7",
    pmid: "34798060",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2022-zimmermann-bi456906",
    title:
      "BI 456906: Discovery and preclinical pharmacology of a novel GCGR/GLP-1R dual agonist with robust anti-obesity efficacy",
    authors: [
      "Zimmermann T",
      "Thomas L",
      "Baader-Pagler T",
      "Haebel P",
      "Simon E",
      "Reindl W",
      "Bajrami B",
      "Rist W",
      "Uphues I",
      "Drucker DJ",
      "Klein H",
      "Santhanam R",
      "Hamprecht D",
      "Neubauer H",
      "Augustin R",
    ],
    publication: "Molecular Metabolism",
    year: 2022,
    doi: "10.1016/j.molmet.2022.101633",
    pmid: "36356832",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2024-sanyal-survodutide-mash",
    title: "A Phase 2 Randomized Trial of Survodutide in MASH and Fibrosis",
    authors: [
      "Sanyal AJ",
      "Bedossa P",
      "Fraessdorf M",
      "Neff GW",
      "Lawitz E",
      "Bugianesi E",
      "Anstee QM",
      "Hussain SA",
      "Newsome PN",
      "Ratziu V",
      "Hosseini-Tabatabaei A",
      "Schattenberg JM",
      "Noureddin M",
      "Alkhouri N",
      "Younes R",
      "1404-0043 Trial Investigators",
    ],
    publication: "The New England Journal of Medicine",
    year: 2024,
    doi: "10.1056/NEJMoa2401755",
    pmid: "38847460",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2026-gao-mazdutide-glory-2",
    title:
      "Treatment With 9-mg Mazdutide for Weight Reduction in Chinese Adults With Obesity: The GLORY-2 Randomized Clinical Trial",
    authors: [
      "Gao L",
      "Jiang H",
      "Cai H",
      "Tian J",
      "Shi B",
      "Qiu W",
      "Huang C",
      "Han J",
      "Zhang S",
      "Pang S",
      "Bi Y",
      "Chen L",
      "Gu X",
      "Han J",
      "Ma Q",
      "Deng H",
      "Wang Y",
      "Li L",
      "Han-Zhang H",
      "Qian L",
      "Ji L",
      "GLORY-2 Trial Investigators",
    ],
    publication: "JAMA",
    year: 2026,
    doi: "10.1001/jama.2026.8142",
    pmid: "42251595",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2026-zhu-mazdutide-t2d",
    title: "Mazdutide versus placebo in Chinese adults with type 2 diabetes",
    authors: [
      "Zhu D",
      "Zhao J",
      "Cai H",
      "Chu X",
      "Xiu S",
      "Song C",
      "Cheng Z",
      "Cao H",
      "Jiang H",
      "Zhang L",
      "Wang H",
      "Shi B",
      "Li Y",
      "Liu M",
      "Feng B",
      "Xue F",
      "Deng H",
      "Li H",
      "Li L",
      "Li Y",
      "Ma Q",
      "Qian L",
    ],
    publication: "Nature",
    year: 2026,
    doi: "10.1038/s41586-025-10026-w",
    pmid: "41407859",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2007-falutz-tesamorelin",
    title: "Metabolic effects of a growth hormone-releasing factor in patients with HIV",
    authors: [
      "Falutz J",
      "Allas S",
      "Blot K",
      "Potvin D",
      "Kotler D",
      "Somero M",
      "Berger D",
      "Brown S",
      "Richmond G",
      "Fessel J",
      "Turner R",
      "Grinspoon S",
    ],
    publication: "The New England Journal of Medicine",
    year: 2007,
    doi: "10.1056/NEJMoa072375",
    pmid: "18057338",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2015-cox-aod9604",
    title: "Detection and in vitro metabolism of AOD9604",
    authors: ["Cox HD", "Smeal SJ", "Hughes CM", "Cox JE", "Eichner D"],
    publication: "Drug Testing and Analysis",
    year: 2015,
    doi: "10.1002/dta.1715",
    pmid: "25208511",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2000-ng-aod9604-zucker",
    title: "Metabolic studies of a synthetic lipolytic domain (AOD9604) of human growth hormone",
    authors: ["Ng FM", "Sun J", "Sharma L", "Libinaka R", "Jiang WJ", "Gianello R"],
    publication: "Hormone Research",
    year: 2000,
    doi: "10.1159/000053183",
    pmid: "11146367",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2001-heffernan-aod9604-mice",
    title:
      "The effects of human GH and its lipolytic fragment (AOD9604) on lipid metabolism following chronic treatment in obese mice and beta(3)-AR knock-out mice",
    authors: [
      "Heffernan M",
      "Summers RJ",
      "Thorburn A",
      "Ogru E",
      "Gianello R",
      "Jiang WJ",
      "Ng FM",
    ],
    publication: "Endocrinology",
    year: 2001,
    doi: "10.1210/endo.142.12.8522",
    pmid: "11713213",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2018-neelakantan-nnmt-inhibitors",
    title:
      "Selective and membrane-permeable small molecule inhibitors of nicotinamide N-methyltransferase reverse high fat diet-induced obesity in mice",
    authors: [
      "Neelakantan H",
      "Vance V",
      "Wetzel MD",
      "Wang HL",
      "McHardy SF",
      "Finnerty CC",
      "Hommel JD",
      "Watowich SJ",
    ],
    publication: "Biochemical Pharmacology",
    year: 2018,
    doi: "10.1016/j.bcp.2017.11.007",
    pmid: "29155147",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2021-roberti-nnmt",
    title:
      "Nicotinamide N-methyltransferase: At the crossroads between cellular metabolism and epigenetic regulation",
    authors: ["Roberti A", "Fernández AF", "Fraga MF"],
    publication: "Molecular Metabolism",
    year: 2021,
    doi: "10.1016/j.molmet.2021.101165",
    pmid: "33453420",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },
  {
    id: "ref-2023-billon-slu-pp-332",
    title:
      "Synthetic ERRα/β/γ Agonist Induces an ERRα-Dependent Acute Aerobic Exercise Response and Enhances Exercise Capacity",
    authors: [
      "Billon C",
      "Sitaula S",
      "Banerjee S",
      "Welch R",
      "Elgendy B",
      "Hegazy L",
      "Oh TG",
      "Kazantzis M",
      "Chatterjee A",
      "Chrivia J",
      "Hayes ME",
      "Xu W",
      "Hamilton A",
      "Huss JM",
      "Zhang L",
      "Walker JK",
      "Downes M",
      "Evans RM",
      "Burris TP",
    ],
    publication: "ACS Chemical Biology",
    year: 2023,
    doi: "10.1021/acschembio.2c00720",
    pmid: "36988910",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2004-kolonin-adipose-ablation",
    title: "Reversal of obesity by targeted ablation of adipose tissue",
    authors: ["Kolonin MG", "Saha PK", "Chan L", "Pasqualini R", "Arap W"],
    publication: "Nature Medicine",
    year: 2004,
    doi: "10.1038/nm1048",
    pmid: "15133506",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2011-barnhart-adipotide-monkeys",
    title:
      "A peptidomimetic targeting white fat causes weight loss and improved insulin resistance in obese monkeys",
    authors: [
      "Barnhart KF",
      "Christianson DR",
      "Hanley PW",
      "Driessen WH",
      "Bernacky BJ",
      "Baze WB",
      "Wen S",
      "Tian M",
      "Ma J",
      "Kolonin MG",
      "Saha PK",
      "Do KA",
      "Hulvat JF",
      "Gelovani JG",
      "Chan L",
      "Arap W",
      "Pasqualini R",
    ],
    publication: "Science Translational Medicine",
    year: 2011,
    doi: "10.1126/scitranslmed.3002621",
    pmid: "22072637",
    url: null,
    sourceType: "journal-article",
    status: BATCH_3,
  },
  {
    id: "ref-2016-longo-carnitine-transport",
    title: "Carnitine transport and fatty acid oxidation",
    authors: ["Longo N", "Frigeni M", "Pasquali M"],
    publication: "Biochimica et Biophysica Acta",
    year: 2016,
    doi: "10.1016/j.bbamcr.2016.01.023",
    pmid: "26828774",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },
  {
    id: "ref-2016-pooyandjoo-carnitine-meta",
    title:
      "The effect of (L-)carnitine on weight loss in adults: a systematic review and meta-analysis of randomized controlled trials",
    authors: ["Pooyandjoo M", "Nouhi M", "Shab-Bidar S", "Djafarian K", "Olyaeemanesh A"],
    publication: "Obesity Reviews",
    year: 2016,
    doi: "10.1111/obr.12436",
    pmid: "27335245",
    url: null,
    sourceType: "review-article",
    status: BATCH_3,
  },

  /* ---- Batch 1: GHK-Cu --------------------------------------------------- */
  {
    id: "ref-2015-pickart-ghk-skin",
    title: "GHK Peptide as a Natural Modulator of Multiple Cellular Pathways in Skin Regeneration",
    authors: ["Pickart L", "Vasquez-Soltero JM", "Margolina A"],
    publication: "BioMed Research International",
    year: 2015,
    doi: "10.1155/2015/648108",
    pmid: "26236730",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-2018-pickart-ghk-cu-gene-data",
    title:
      "Regenerative and Protective Actions of the GHK-Cu Peptide in the Light of the New Gene Data",
    authors: ["Pickart L", "Margolina A"],
    publication: "International Journal of Molecular Sciences",
    year: 2018,
    doi: "10.3390/ijms19071987",
    pmid: "29986520",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },

  /* ---- Batch 1: BPC-157 and TB-500 --------------------------------------- */
  {
    id: "ref-2025-vasireddi-bpc157-review",
    title: "Emerging Use of BPC-157 in Orthopaedic Sports Medicine: A Systematic Review",
    authors: [
      "Vasireddi N",
      "Hahamyan H",
      "Salata MJ",
      "Karns M",
      "Calcei JG",
      "Voos JE",
      "Apostolakos JM",
    ],
    publication: "HSS Journal",
    year: 2025,
    doi: "10.1177/15563316251355551",
    pmid: "40756949",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-2012-goldstein-thymosin-b4",
    title:
      "Thymosin β4: a multi-functional regenerative peptide. Basic properties and clinical applications",
    authors: ["Goldstein AL", "Hannappel E", "Sosne G", "Kleinman HK"],
    publication: "Expert Opinion on Biological Therapy",
    year: 2012,
    doi: "10.1517/14712598.2012.634793",
    pmid: "22074294",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
  {
    id: "ref-1999-malinda-thymosin-b4-wound",
    title: "Thymosin beta4 accelerates wound healing",
    authors: [
      "Malinda KM",
      "Sidhu GS",
      "Mani H",
      "Banaudha K",
      "Maheshwari RK",
      "Goldstein AL",
      "Kleinman HK",
    ],
    publication: "The Journal of Investigative Dermatology",
    year: 1999,
    doi: "10.1046/j.1523-1747.1999.00708.x",
    pmid: "10469335",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },
  {
    id: "ref-2026-bicer-bpc157-tb500-achilles",
    title:
      "Effects of BPC-157 and TB-500 on Achilles tendon healing in rats: A histopathological and biomechanical study",
    authors: [
      "Biçer O",
      "Adanir O",
      "Güleryüz Y",
      "Balci EC",
      "Dinçel YM",
      "Yenigün MY",
      "Aydin C",
      "Bayrak BY",
    ],
    publication: "Joint Diseases and Related Surgery",
    year: 2026,
    doi: "10.52312/jdrs.2026.2951",
    pmid: "42542926",
    url: null,
    sourceType: "journal-article",
    status: BATCH_1,
  },

  /* ---- Batch 1: shared --------------------------------------------------- */
  {
    id: "ref-2026-tewari-peptide-supplements",
    title: "Peptide Supplements and Their Therapeutic Applications in Sports Medicine",
    authors: ["Tewari K", "Liu TP", "Im C", "Hamad C", "Petrigliano F", "Cheung EC", "Kremen TJ"],
    publication: "The American Journal of Sports Medicine",
    year: 2026,
    doi: "10.1177/03635465261464420",
    pmid: "42578445",
    url: null,
    sourceType: "review-article",
    status: BATCH_1,
  },
];
